service: numa-backend
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  api:
    handler: src/main/server.handler
    timeout: 30
    events:
      - httpApi: '*'

plugins:
  - serverless-plugin-typescript
  - serverless-offline
